# Generated by Django 2.1.7 on 2019-03-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='link',
            field=models.CharField(default='http://facebook.com', max_length=200),
        ),
    ]
